version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: patitas_sanas_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin_vet
      POSTGRES_PASSWORD: secretpassword123
      POSTGRES_DB: patitas_sanas
      TZ: America/Mexico_City
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
  